### ISSUE TITLE
Small mistake in rule element; Persistent damage not applying correctly

### ISSUE THREAD

**Issue by emomgo3** [jmerlin-nerd/elemental-ammunition-for-pf2e#1]
There is a small issue in the rule elements of all added ammunitions, leading to the persistent damage not applying on the attack.

Instead of:
{
  "key": "DamageDice",

  **"selector": "{item_id}-damage",**

  "dieSize": "d4",
  "diceNumber": 3,
  "damageType": "acid",
  "category": "persistent",
  "label": "Persistent Acid"
}

it should be:

{
  "key": "DamageDice",

  **"selector": "{item|_id}-damage",**

  "dieSize": "d4",
  "diceNumber": 3,
  "damageType": "acid",
  "category": "persistent",
  "label": "Persistent Acid"
}

**Comment by jmerlin-nerd** [comment]
Thank you! This should have been fixed in v12.0.0.
Again, thanks
