### ISSUE TITLE
Wrong zip name

### ISSUE THREAD

**Issue by Lioheart** [jmerlin-nerd/elemental-ammunition-for-pf2e#8]
In the module.json file, the name of the zip file contains a “-” and the package has a dot between “pf2e” and the version.

`"download": "https://github.com/jmerlin-nerd/elemental-ammunition-for-pf2e/releases/download/v12.0.3/elemental-ammunition-for-pf2e-v12.0.3.zip"`

![obraz](https://github.com/user-attachments/assets/29081450-5e68-492b-9238-f3ae57c80865)

**Comment by jmerlin-nerd** [comment]
Thank you for bringing this up. v12.0.6 should fix this problem, and prevent it from being an issue in the future.
